### ISSUE TITLE
Implementar roteamento

### ISSUE THREAD

**Issue by weltonfelix** [ifpeopensource/merenda-josueapp#7]
Sugiro utilizar a lib [React Router](https://reactrouter.com/).

**Comment by carvalhoedsonn** [comment]
Antes de fazer isso precisamos definir como será o esquema de pastas em que irá conter os arquivos das diferentes páginas (login, home, etc).

**Comment by weltonfelix** [comment]
Implementado em bb921c7d7f4ecb06d3d6f33937abe63fee24488e.
